[package]
name = "yy_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solution_iter = { path = "../solution_iter" }
strength_reduce = "0.2"
tokio-util = "0.7"
