[package]
name = "solution_iter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-util = "0.7"

[dev-dependencies]
sudoku_engine = { path = "../sudoku_engine" }
